<?php
get_template_part('widgets/flickr-widget');
get_template_part('widgets/social-widget');
get_template_part('widgets/sponsors-post');
get_template_part('widgets/schedule-widget');
get_template_part('widgets/timeline-widget');
get_template_part('widgets/latest-blog-posts');
get_template_part('widgets/map-highlight');
get_template_part('widgets/single-highlight');
?>